### ISSUE TITLE
What can we re-use from OpenAire DataCite profile & recomendations?

### ISSUE THREAD

**Issue by borsna** [researchdata-se/docs.researchdata.se#2]
OpenAire have compiled a set of recomendations and suggestions for DataCite:
https://guidelines.openaire.eu/en/latest/data/use_of_datacite.html

This could be a good source for the recommendations.

**Comment by borsna** [comment]
@jomtov added your examples to the list https://docs.researchdata.se/metadata/datacite-xml/

**Comment by jomtov** [comment]
Corrected example typos above in three places: _affiiationIdentifierScheme_  -> **affiliationIdentifierScheme**. 
Please update and do the same in https://docs.researchdata.se/metadata/datacite-xml!

**Comment by borsna** [comment]
@jomtov fixed in https://github.com/researchdata-se/docs.researchdata.se/commit/ca7070288e325955afbd4ac7309c093931472524
